using IAutoM8.Global.Options;

namespace IAutoM8.Global
{
    public static class UserRolePermissions
    {
        public static RolePermissions Owner = new RolePermissions
        {
            FormulasPage = true,
            CreateFormula = true,
            EditFormulaInfo = true,
            DeletFormula = true,
            ViewFormula = true,
            AccessToFormulaUiEditor = true,
            CreateProjectFromFormula = true,
            LockFormula = true,

            FormulaModalWindow = true,
            SetFormulaOwner = true,
            SetFormulaMembers = true,
            AddFormulaFiles = true,
            ShareFormula = true,
            CopyFormulaFromShareLink = true,

            FormulaUiEditor = true,
            FormulaUiEditorCreateTask = true,
            FormulaUiEditorEditTask = true,
            FormulaUiEditorDeleteTask = true,
            FormulaUiEditorAddTaskConnection = true,
            FormulaUiEditorRemoveTaskConnection = true,
            
            FormulaTaskEditorModal = true,
            FormulaTaskEditorModalViewNotEdit = true,
            FormulaTaskEditorModalSetStartDate = true,
            FormulaTaskEditorModalSetDueDate = true,
            FormulaTaskEditorModalSetDuration = true,
            FormulaTaskEditorModalSetMembers = true,
            FormulaTaskEditorModalSetRecurringOptions = true,
            FormulaTaskEditorModalProfiles = true,
            FormulaTaskEditorModalFiles = true,
            FormulaTaskEditorModalEditCondition = true,
            FormulaTaskEditorModalAddConditionOption = true,
            FormulaTaskEditorModalEditConditionOption = true,
            FormulaTaskEditorModalDeleteConditionOption = true,
            FormulaTaskEditorModalAssignConditionOptionToTask = true,
            FormulaTaskEditorModalCreateChecklist = true,
            FormulaTaskEditorModalEditChecklist = true,
            FormulaTaskEditorModalDeleteChecklistItem = true,
            FormulaTaskEditorModalToggleChecklistItem = true,

            ProjectsPage = true,
            CreateProject = true,
            EditProject = true,
            DeleteProject = true,
            ViewKanbanBoard = true,
            AccessToProjectUiEditor = true,

            ProjectModalWindow = true,
            SetProjectOwner = true,
            SetProjectMembers = true,
            SetProjectClient = true,
            AddProjectFiles = true,

            ChangeProjectTaskStatus = true,
            ImportTasksFromFormula = true,
            CreateProjectTask = true,
            EditProjectTask = true,
            DeleteProjectTask = true,
            SelectOptionOnCompleteProjectTask = true,
            ChangeChecklistItemStatus = true,
            FilterTasksBySkill = true,
            FilterTasksByUser = true,

            ProjectUiEditorCreateTask = true,
            ProjectUiEditorEditTask = true,
            ProjectUiEditorDeleteTask = true,
            ProjectUiEditorAddTaskConnection = true,
            ProjectUiEditorRemoveTaskConnection = true,

            CanChangeProcessingUser = true,
            CanAssignVendor = true,
            CanStopOutsource = true,
            ProjectTaskEditorModal = true,
            ProjectTaskEditorModalViewNotEdit = false,
            ProjectTaskEditorModalSetStartDate = true,
            ProjectTaskEditorModalSetDueDate = true,
            ProjectTaskEditorModalSetDuration = true,
            ProjectTaskEditorModalSetMembers = true,
            ProjectTaskEditorModalSetRecurringOptions = true,
            ProjectTaskEditorModalProfiles = true,
            ProjectTaskEditorModalFiles = true,
            ProjectTaskEditorModalEditCondition = true,
            ProjectTaskEditorModalAddConditionOption = true,
            ProjectTaskEditorModalEditConditionOption = true,
            ProjectTaskEditorModalDeleteConditionOption = true,
            ProjectTaskEditorModalAssignConditionOptionToTask = true,
            ProjectTaskEditorModalCreateChecklist = true,
            ProjectTaskEditorModalEditChecklist = true,
            ProjectTaskEditorModalDeleteChecklistItem = true,
            ProjectTaskEditorModalToggleChecklistItem = true,

            UsersPage = true,
            CreateUser = true,
            EditUsersName = true,
            ChangeUsersRole = true,
            DeleteUser = true,
            LockUser = true,
            UnlockUser = true,
            EditUserNotificationSettings = true,
            EditRoleNotificationSettings = true,

            EditOwnerBusinessDetails = true,
            ViewOwnerBusinessDetails = true,

            SkillsPage = true,
            TeamsPage = true,
            CreateTeam = true,
            ReadSkill = true,
            CreateSkill = true,
            EditSkill = true,
            DeleteSkill = true,
            AssignSkill = true,
            ReadUserSkill = true,
            AddUserToSkill = true,

            ClientsPage = true,
            CreateClient = true,
            ReadClient = true,
            EditClient = true,
            DeleteClient = true,
            AssignProjectToClient = true,

            BalancePage = false,
            CreditsPage = true,

            ViewMissionControl = false,

            ViewUpSkills = false,

            FormulaTaskLockTraining = false,
        };

        public static RolePermissions Manager = new RolePermissions
        {
            FormulasPage = true,
            CreateFormula = true,
            EditFormulaInfo = true,
            DeletFormula = false,
            ViewFormula = true,
            AccessToFormulaUiEditor = true,
            CreateProjectFromFormula = true,
            LockFormula = false,

            FormulaModalWindow = true,
            SetFormulaOwner = false,
            SetFormulaMembers = true,
            AddFormulaFiles = true,
            ShareFormula = false,
            CopyFormulaFromShareLink = false,

            FormulaUiEditor = true,
            FormulaUiEditorCreateTask = true,
            FormulaUiEditorEditTask = true,
            FormulaUiEditorDeleteTask = true,
            FormulaUiEditorAddTaskConnection = true,
            FormulaUiEditorRemoveTaskConnection = true,

            FormulaTaskEditorModal = true,
            FormulaTaskEditorModalViewNotEdit = false,
            FormulaTaskEditorModalSetStartDate = true,
            FormulaTaskEditorModalSetDueDate = true,
            FormulaTaskEditorModalSetDuration = true,
            FormulaTaskEditorModalSetMembers = true,
            FormulaTaskEditorModalSetRecurringOptions = true,
            FormulaTaskEditorModalProfiles = true,
            FormulaTaskEditorModalFiles = true,
            FormulaTaskEditorModalEditCondition = true,
            FormulaTaskEditorModalAddConditionOption = true,
            FormulaTaskEditorModalEditConditionOption = true,
            FormulaTaskEditorModalDeleteConditionOption = true,
            FormulaTaskEditorModalAssignConditionOptionToTask = true,
            FormulaTaskEditorModalCreateChecklist = true,
            FormulaTaskEditorModalEditChecklist = true,
            FormulaTaskEditorModalDeleteChecklistItem = true,
            FormulaTaskEditorModalToggleChecklistItem = true,

            ProjectsPage = true,
            CreateProject = true,
            EditProject = true,
            DeleteProject = true,
            ViewKanbanBoard = true,
            AccessToProjectUiEditor = true,

            ProjectModalWindow = true,
            SetProjectOwner = false,
            SetProjectMembers = false,
            SetProjectClient = false,
            AddProjectFiles = false,

            ChangeProjectTaskStatus = true,
            ImportTasksFromFormula = true,
            CreateProjectTask = true,
            EditProjectTask = true,
            DeleteProjectTask = true,
            SelectOptionOnCompleteProjectTask = true,
            ChangeChecklistItemStatus = true,
            FilterTasksBySkill = true,
            FilterTasksByUser = true,

            ProjectUiEditorCreateTask = true,
            ProjectUiEditorEditTask = true,
            ProjectUiEditorDeleteTask = true,
            ProjectUiEditorAddTaskConnection = true,
            ProjectUiEditorRemoveTaskConnection = true,

            CanChangeProcessingUser = true,
            CanAssignVendor = true,
            CanStopOutsource = true,
            ProjectTaskEditorModal = true,
            ProjectTaskEditorModalViewNotEdit = false,
            ProjectTaskEditorModalSetStartDate = true,
            ProjectTaskEditorModalSetDueDate = true,
            ProjectTaskEditorModalSetDuration = true,
            ProjectTaskEditorModalSetMembers = true,
            ProjectTaskEditorModalSetRecurringOptions = true,
            ProjectTaskEditorModalProfiles = true,
            ProjectTaskEditorModalFiles = true,
            ProjectTaskEditorModalEditCondition = true,
            ProjectTaskEditorModalAddConditionOption = true,
            ProjectTaskEditorModalEditConditionOption = true,
            ProjectTaskEditorModalDeleteConditionOption = true,
            ProjectTaskEditorModalAssignConditionOptionToTask = true,
            ProjectTaskEditorModalCreateChecklist = true,
            ProjectTaskEditorModalEditChecklist = true,
            ProjectTaskEditorModalDeleteChecklistItem = true,
            ProjectTaskEditorModalToggleChecklistItem = true,

            UsersPage = true,
            CreateUser = true,
            EditUsersName = true,
            ChangeUsersRole = true,
            DeleteUser = true,
            LockUser = true,
            UnlockUser = true,
            EditUserNotificationSettings = true,
            EditRoleNotificationSettings = false,

            EditOwnerBusinessDetails = false, 
            ViewOwnerBusinessDetails = false,

            SkillsPage = true,
            TeamsPage = true,
            CreateTeam = true,
            ReadSkill = true,
            CreateSkill = true,
            EditSkill = true,
            DeleteSkill = true,
            AssignSkill = true,
            ReadUserSkill = true,
            AddUserToSkill = true,

            ClientsPage = true,
            CreateClient = true,
            ReadClient = true,
            EditClient = true,
            DeleteClient = true,
            AssignProjectToClient = true,

            BalancePage = false,
            CreditsPage = false,

            ViewMissionControl = false,

            ViewUpSkills = false,

            FormulaTaskLockTraining = false,
        };

        public static RolePermissions Worker = new RolePermissions
        {
            FormulasPage = false,
            CreateFormula = false,
            EditFormulaInfo = false,
            DeletFormula = false,
            ViewFormula = false,
            AccessToFormulaUiEditor = false,
            CreateProjectFromFormula = false,
            LockFormula = false,

            FormulaModalWindow = false,
            SetFormulaOwner = false,
            SetFormulaMembers = false,
            AddFormulaFiles = false,
            ShareFormula = false,
            CopyFormulaFromShareLink = false,

            FormulaUiEditor = false,
            FormulaUiEditorCreateTask = false,
            FormulaUiEditorEditTask = false,
            FormulaUiEditorDeleteTask = false,
            FormulaUiEditorRemoveTaskConnection = false,
            FormulaUiEditorAddTaskConnection = false,

            FormulaTaskEditorModal = true,
            FormulaTaskEditorModalViewNotEdit = true,
            FormulaTaskEditorModalSetStartDate = false,
            FormulaTaskEditorModalSetDueDate = false,
            FormulaTaskEditorModalSetDuration = false,
            FormulaTaskEditorModalSetMembers = false,
            FormulaTaskEditorModalSetRecurringOptions = false,
            FormulaTaskEditorModalProfiles = false,
            FormulaTaskEditorModalFiles = true,
            FormulaTaskEditorModalEditCondition = false,
            FormulaTaskEditorModalAddConditionOption = false,
            FormulaTaskEditorModalEditConditionOption = false,
            FormulaTaskEditorModalDeleteConditionOption = false,
            FormulaTaskEditorModalAssignConditionOptionToTask = false,
            FormulaTaskEditorModalCreateChecklist = false,
            FormulaTaskEditorModalEditChecklist = false,
            FormulaTaskEditorModalDeleteChecklistItem = false,
            FormulaTaskEditorModalToggleChecklistItem = true,

            ProjectsPage = true,
            CreateProject = false,
            EditProject = false,
            DeleteProject = false,
            ViewKanbanBoard = true,
            AccessToProjectUiEditor = false,

            ProjectModalWindow = false,
            SetProjectOwner = false,
            SetProjectMembers = false,
            SetProjectClient = false,
            AddProjectFiles = false,

            ChangeProjectTaskStatus = true,
            ImportTasksFromFormula = false,
            CreateProjectTask = false,
            EditProjectTask = false,
            DeleteProjectTask = false,
            SelectOptionOnCompleteProjectTask = false,
            ChangeChecklistItemStatus = true,
            FilterTasksBySkill = false,
            FilterTasksByUser = false,

            ProjectUiEditorCreateTask = false,
            ProjectUiEditorEditTask = false,
            ProjectUiEditorDeleteTask = false,
            ProjectUiEditorAddTaskConnection = false,
            ProjectUiEditorRemoveTaskConnection = false,

            CanChangeProcessingUser = false,
            CanAssignVendor = false,
            CanStopOutsource = false,
            ProjectTaskEditorModal = true,
            ProjectTaskEditorModalViewNotEdit = true,
            ProjectTaskEditorModalSetStartDate = false,
            ProjectTaskEditorModalSetDueDate = false,
            ProjectTaskEditorModalSetDuration = false,
            ProjectTaskEditorModalSetMembers = false,
            ProjectTaskEditorModalSetRecurringOptions = false,
            ProjectTaskEditorModalProfiles = false,
            ProjectTaskEditorModalFiles = true,
            ProjectTaskEditorModalEditCondition = false,
            ProjectTaskEditorModalAddConditionOption = false,
            ProjectTaskEditorModalEditConditionOption = false,
            ProjectTaskEditorModalDeleteConditionOption = false,
            ProjectTaskEditorModalAssignConditionOptionToTask = false,
            ProjectTaskEditorModalCreateChecklist = false,
            ProjectTaskEditorModalEditChecklist = false,
            ProjectTaskEditorModalDeleteChecklistItem = false,
            ProjectTaskEditorModalToggleChecklistItem = true,

            UsersPage = false,
            CreateUser = false,
            EditUsersName = true,
            ChangeUsersRole = false,
            DeleteUser = false,
            LockUser = false,
            UnlockUser = false,
            EditUserNotificationSettings = false,
            EditRoleNotificationSettings = false,

            EditOwnerBusinessDetails = false,
            ViewOwnerBusinessDetails = false,

            SkillsPage = false,
            TeamsPage = false,
            CreateTeam = false,
            ReadSkill = false,
            CreateSkill = false,
            EditSkill = false,
            DeleteSkill = false,
            AssignSkill = false,
            ReadUserSkill = true,
            AddUserToSkill = false,

            ClientsPage = false,
            CreateClient = false,
            ReadClient = false,
            EditClient = false,
            DeleteClient = false,
            AssignProjectToClient = false,

            BalancePage = false,
            CreditsPage = false,

            ViewMissionControl = false,

            ViewUpSkills = false,

            FormulaTaskLockTraining = false,
        };

        public static RolePermissions Vendor = new RolePermissions
        {
            FormulasPage = false,
            CreateFormula = false,
            EditFormulaInfo = false,
            DeletFormula = false,
            ViewFormula = false,
            AccessToFormulaUiEditor = false,
            CreateProjectFromFormula = false,
            LockFormula = false,

            FormulaModalWindow = false,
            SetFormulaOwner = false,
            SetFormulaMembers = false,
            AddFormulaFiles = false,
            ShareFormula = false,
            CopyFormulaFromShareLink = false,

            FormulaUiEditor = false,
            FormulaUiEditorCreateTask = false,
            FormulaUiEditorEditTask = false,
            FormulaUiEditorDeleteTask = false,
            FormulaUiEditorRemoveTaskConnection = false,
            FormulaUiEditorAddTaskConnection = false,

            FormulaTaskEditorModal = true,
            FormulaTaskEditorModalViewNotEdit = true,
            FormulaTaskEditorModalSetStartDate = false,
            FormulaTaskEditorModalSetDueDate = false,
            FormulaTaskEditorModalSetDuration = false,
            FormulaTaskEditorModalSetMembers = false,
            FormulaTaskEditorModalSetRecurringOptions = false,
            FormulaTaskEditorModalProfiles = false,
            FormulaTaskEditorModalFiles = true,
            FormulaTaskEditorModalEditCondition = false,
            FormulaTaskEditorModalAddConditionOption = false,
            FormulaTaskEditorModalEditConditionOption = false,
            FormulaTaskEditorModalDeleteConditionOption = false,
            FormulaTaskEditorModalAssignConditionOptionToTask = false,
            FormulaTaskEditorModalCreateChecklist = false,
            FormulaTaskEditorModalEditChecklist = false,
            FormulaTaskEditorModalDeleteChecklistItem = false,
            FormulaTaskEditorModalToggleChecklistItem = true,

            ProjectsPage = true,
            CreateProject = false,
            EditProject = false,
            DeleteProject = false,
            ViewKanbanBoard = true,
            AccessToProjectUiEditor = true,

            ProjectModalWindow = false,
            SetProjectOwner = false,
            SetProjectMembers = false,
            SetProjectClient = false,
            AddProjectFiles = false,

            ChangeProjectTaskStatus = true,
            ImportTasksFromFormula = false,
            CreateProjectTask = false,
            EditProjectTask = false,
            DeleteProjectTask = false,
            SelectOptionOnCompleteProjectTask = false,
            ChangeChecklistItemStatus = true,
            FilterTasksBySkill = false,
            FilterTasksByUser = false,

            ProjectUiEditorCreateTask = false,
            ProjectUiEditorEditTask = false,
            ProjectUiEditorDeleteTask = false,
            ProjectUiEditorAddTaskConnection = false,
            ProjectUiEditorRemoveTaskConnection = false,

            CanChangeProcessingUser = false,
            CanAssignVendor = false,
            CanStopOutsource = true,
            ProjectTaskEditorModal = true,
            ProjectTaskEditorModalViewNotEdit = true,
            ProjectTaskEditorModalSetStartDate = false,
            ProjectTaskEditorModalSetDueDate = false,
            ProjectTaskEditorModalSetDuration = false,
            ProjectTaskEditorModalSetMembers = false,
            ProjectTaskEditorModalSetRecurringOptions = false,
            ProjectTaskEditorModalProfiles = false,
            ProjectTaskEditorModalFiles = true,
            ProjectTaskEditorModalEditCondition = false,
            ProjectTaskEditorModalAddConditionOption = false,
            ProjectTaskEditorModalEditConditionOption = false,
            ProjectTaskEditorModalDeleteConditionOption = false,
            ProjectTaskEditorModalAssignConditionOptionToTask = false,
            ProjectTaskEditorModalCreateChecklist = false,
            ProjectTaskEditorModalEditChecklist = false,
            ProjectTaskEditorModalDeleteChecklistItem = false,
            ProjectTaskEditorModalToggleChecklistItem = true,

            UsersPage = false,
            CreateUser = false,
            EditUsersName = true,
            ChangeUsersRole = false,
            DeleteUser = false,
            LockUser = false,
            UnlockUser = false,
            EditUserNotificationSettings = false,
            EditRoleNotificationSettings = false,

            EditOwnerBusinessDetails = false,
            ViewOwnerBusinessDetails = false,

            SkillsPage = false,
            TeamsPage = false,
            CreateTeam = false,
            ReadSkill = false,
            CreateSkill = false,
            EditSkill = false,
            DeleteSkill = false,
            AssignSkill = false,
            ReadUserSkill = true,
            AddUserToSkill = false,

            ClientsPage = false,
            CreateClient = false,
            ReadClient = false,
            EditClient = false,
            DeleteClient = false,
            AssignProjectToClient = false,

            BalancePage = true,
            CreditsPage = false,

            ViewMissionControl = true,

            ViewUpSkills = true,

            FormulaTaskLockTraining = false,
        };

        public static RolePermissions Admin = new RolePermissions
        {
            FormulasPage = true,
            CreateFormula = true,
            EditFormulaInfo = true,
            DeletFormula = true,
            ViewFormula = true,
            AccessToFormulaUiEditor = true,
            CreateProjectFromFormula = true,
            LockFormula = true,
            TeamsPage = true,
            CreateTeam = true,
            EditSkill =true,

           

            FormulaModalWindow = true,
            SetFormulaOwner = true,
            SetFormulaMembers = true,
            AddFormulaFiles = true,
            ShareFormula = true,
            CopyFormulaFromShareLink = true,

            FormulaUiEditor = true,
            FormulaUiEditorCreateTask = true,
            FormulaUiEditorEditTask = true,
            FormulaUiEditorDeleteTask = true,
            FormulaUiEditorAddTaskConnection = true,
            FormulaUiEditorRemoveTaskConnection = true,

            FormulaTaskEditorModal = true,
            FormulaTaskEditorModalViewNotEdit = true,
            FormulaTaskEditorModalSetStartDate = true,
            FormulaTaskEditorModalSetDueDate = true,
            FormulaTaskEditorModalSetDuration = true,
            FormulaTaskEditorModalSetMembers = true,
            FormulaTaskEditorModalSetRecurringOptions = true,
            FormulaTaskEditorModalProfiles = true,
            FormulaTaskEditorModalFiles = true,
            FormulaTaskEditorModalEditCondition = true,
            FormulaTaskEditorModalAddConditionOption = true,
            FormulaTaskEditorModalEditConditionOption = true,
            FormulaTaskEditorModalDeleteConditionOption = true,
            FormulaTaskEditorModalAssignConditionOptionToTask = true,
            FormulaTaskEditorModalCreateChecklist = true,
            FormulaTaskEditorModalEditChecklist = true,
            FormulaTaskEditorModalDeleteChecklistItem = true,
            FormulaTaskEditorModalToggleChecklistItem = true,

            ProjectsPage = false,
            CreateProject = true,
            EditProject = true,
            DeleteProject = true,
            ViewKanbanBoard = true,
            AccessToProjectUiEditor = true,

            ProjectModalWindow = true,
            SetProjectOwner = true,
            SetProjectMembers = true,
            SetProjectClient = true,
            AddProjectFiles = true,

            ChangeProjectTaskStatus = true,
            ImportTasksFromFormula = true,
            CreateProjectTask = true,
            EditProjectTask = true,
            DeleteProjectTask = true,
            SelectOptionOnCompleteProjectTask = true,
            ChangeChecklistItemStatus = true,
            FilterTasksBySkill = true,
            FilterTasksByUser = true,

            ProjectUiEditorCreateTask = true,
            ProjectUiEditorEditTask = true,
            ProjectUiEditorDeleteTask = true,
            ProjectUiEditorAddTaskConnection = true,
            ProjectUiEditorRemoveTaskConnection = true,

           

            EditUserNotificationSettings = true,
            EditRoleNotificationSettings = true,

            EditOwnerBusinessDetails = true,
            ViewOwnerBusinessDetails = true,

            adminUsersPage = true,
            Payment =true,

            CanChangeProcessingUser = true,
            CanAssignVendor = true,
            CanStopOutsource = true,
            ProjectTaskEditorModal = true,
            ProjectTaskEditorModalViewNotEdit = false,
            ProjectTaskEditorModalSetStartDate = true,
            ProjectTaskEditorModalSetDueDate = true,
            ProjectTaskEditorModalSetDuration = true,
            ProjectTaskEditorModalSetMembers = true,
            ProjectTaskEditorModalSetRecurringOptions = true,
            ProjectTaskEditorModalProfiles = true,
            ProjectTaskEditorModalFiles = true,
            ProjectTaskEditorModalEditCondition = true,
            ProjectTaskEditorModalAddConditionOption = true,
            ProjectTaskEditorModalEditConditionOption = true,
            ProjectTaskEditorModalDeleteConditionOption = true,
            ProjectTaskEditorModalAssignConditionOptionToTask = true,
            ProjectTaskEditorModalCreateChecklist = true,
            ProjectTaskEditorModalEditChecklist = true,
            ProjectTaskEditorModalDeleteChecklistItem = true,
            ProjectTaskEditorModalToggleChecklistItem = true,

            UsersPage = false,
            CreateUser = true,
            EditUsersName = true,
            ChangeUsersRole = true,
            DeleteUser = true,
            LockUser = true,
            UnlockUser = true,

            SkillsPage = true,
            ReadSkill = true,
            CreateSkill = true,
            DeleteSkill = true,
            AssignSkill = true,
            ReadUserSkill = true,
            AddUserToSkill = true,

            ClientsPage = false,
            CreateClient = true,
            ReadClient = true,
            EditClient = true,
            DeleteClient = true,
            AssignProjectToClient = true,

            BalancePage = false,
            CreditsPage = false,

            ViewMissionControl = false,

            ViewUpSkills = false,

            FormulaTaskLockTraining = true,
        };

        public static RolePermissions CompanyWoker = new RolePermissions
        {
            FormulasPage = false,
            CreateFormula = false,
            EditFormulaInfo = false,
            DeletFormula = false,
            ViewFormula = false,
            AccessToFormulaUiEditor = false,
            CreateProjectFromFormula = false,
            LockFormula = false,

            FormulaModalWindow = false,
            SetFormulaOwner = false,
            SetFormulaMembers = false,
            AddFormulaFiles = false,
            ShareFormula = false,
            CopyFormulaFromShareLink = false,

            FormulaUiEditor = false,
            FormulaUiEditorCreateTask = false,
            FormulaUiEditorEditTask = false,
            FormulaUiEditorDeleteTask = false,
            FormulaUiEditorRemoveTaskConnection = false,
            FormulaUiEditorAddTaskConnection = false,

            FormulaTaskEditorModal = true,
            FormulaTaskEditorModalViewNotEdit = true,
            FormulaTaskEditorModalSetStartDate = false,
            FormulaTaskEditorModalSetDueDate = false,
            FormulaTaskEditorModalSetDuration = false,
            FormulaTaskEditorModalSetMembers = false,
            FormulaTaskEditorModalSetRecurringOptions = false,
            FormulaTaskEditorModalProfiles = false,
            FormulaTaskEditorModalFiles = true,
            FormulaTaskEditorModalEditCondition = false,
            FormulaTaskEditorModalAddConditionOption = false,
            FormulaTaskEditorModalEditConditionOption = false,
            FormulaTaskEditorModalDeleteConditionOption = false,
            FormulaTaskEditorModalAssignConditionOptionToTask = false,
            FormulaTaskEditorModalCreateChecklist = false,
            FormulaTaskEditorModalEditChecklist = false,
            FormulaTaskEditorModalDeleteChecklistItem = false,
            FormulaTaskEditorModalToggleChecklistItem = true,

            ProjectsPage = true,
            CreateProject = false,
            EditProject = false,
            DeleteProject = false,
            ViewKanbanBoard = true,
            AccessToProjectUiEditor = true,

            ProjectModalWindow = false,
            SetProjectOwner = false,
            SetProjectMembers = false,
            SetProjectClient = false,
            AddProjectFiles = false,

            ChangeProjectTaskStatus = true,
            ImportTasksFromFormula = false,
            CreateProjectTask = false,
            EditProjectTask = false,
            DeleteProjectTask = false,
            SelectOptionOnCompleteProjectTask = false,
            ChangeChecklistItemStatus = true,
            FilterTasksBySkill = false,
            FilterTasksByUser = false,

            ProjectUiEditorCreateTask = false,
            ProjectUiEditorEditTask = false,
            ProjectUiEditorDeleteTask = false,
            ProjectUiEditorAddTaskConnection = false,
            ProjectUiEditorRemoveTaskConnection = false,

            CanChangeProcessingUser = false,
            CanAssignVendor = false,
            CanStopOutsource = true,
            ProjectTaskEditorModal = true,
            ProjectTaskEditorModalViewNotEdit = true,
            ProjectTaskEditorModalSetStartDate = false,
            ProjectTaskEditorModalSetDueDate = false,
            ProjectTaskEditorModalSetDuration = false,
            ProjectTaskEditorModalSetMembers = false,
            ProjectTaskEditorModalSetRecurringOptions = false,
            ProjectTaskEditorModalProfiles = false,
            ProjectTaskEditorModalFiles = true,
            ProjectTaskEditorModalEditCondition = false,
            ProjectTaskEditorModalAddConditionOption = false,
            ProjectTaskEditorModalEditConditionOption = false,
            ProjectTaskEditorModalDeleteConditionOption = false,
            ProjectTaskEditorModalAssignConditionOptionToTask = false,
            ProjectTaskEditorModalCreateChecklist = false,
            ProjectTaskEditorModalEditChecklist = false,
            ProjectTaskEditorModalDeleteChecklistItem = false,
            ProjectTaskEditorModalToggleChecklistItem = true,

            UsersPage = false,
            CreateUser = false,
            EditUsersName = true,
            ChangeUsersRole = false,
            DeleteUser = false,
            LockUser = false,
            UnlockUser = false,
            EditUserNotificationSettings = false,
            EditRoleNotificationSettings = false,

            EditOwnerBusinessDetails = false,
            ViewOwnerBusinessDetails = false,

            SkillsPage = false,
            TeamsPage = false,
            CreateTeam = false,
            ReadSkill = false,
            CreateSkill = false,
            EditSkill = false,
            DeleteSkill = false,
            AssignSkill = false,
            ReadUserSkill = true,
            AddUserToSkill = false,

            ClientsPage = false,
            CreateClient = false,
            ReadClient = false,
            EditClient = false,
            DeleteClient = false,
            AssignProjectToClient = false,

            BalancePage = true,
            CreditsPage = false,

            ViewMissionControl = true,

            ViewUpSkills = true,

            FormulaTaskLockTraining = false,
        }; // added new for company worker (WRT Sprint 10B)

        public static RolePermissions Company = new RolePermissions
        {
            FormulasPage = false,
            CreateFormula = false,
            EditFormulaInfo = false,
            DeletFormula = false,
            ViewFormula = false,
            AccessToFormulaUiEditor = false,
            CreateProjectFromFormula = false,
            LockFormula = false,

            FormulaModalWindow = false,
            SetFormulaOwner = false,
            SetFormulaMembers = false,
            AddFormulaFiles = false,
            ShareFormula = false,
            CopyFormulaFromShareLink = false,

            FormulaUiEditor = false,
            FormulaUiEditorCreateTask = false,
            FormulaUiEditorEditTask = false,
            FormulaUiEditorDeleteTask = false,
            FormulaUiEditorRemoveTaskConnection = false,
            FormulaUiEditorAddTaskConnection = false,

            FormulaTaskEditorModal = true,
            FormulaTaskEditorModalViewNotEdit = true,
            FormulaTaskEditorModalSetStartDate = false,
            FormulaTaskEditorModalSetDueDate = false,
            FormulaTaskEditorModalSetDuration = false,
            FormulaTaskEditorModalSetMembers = false,
            FormulaTaskEditorModalSetRecurringOptions = false,
            FormulaTaskEditorModalProfiles = false,
            FormulaTaskEditorModalFiles = true,
            FormulaTaskEditorModalEditCondition = false,
            FormulaTaskEditorModalAddConditionOption = false,
            FormulaTaskEditorModalEditConditionOption = false,
            FormulaTaskEditorModalDeleteConditionOption = false,
            FormulaTaskEditorModalAssignConditionOptionToTask = false,
            FormulaTaskEditorModalCreateChecklist = false,
            FormulaTaskEditorModalEditChecklist = false,
            FormulaTaskEditorModalDeleteChecklistItem = false,
            FormulaTaskEditorModalToggleChecklistItem = true,

            ProjectsPage = true,
            CreateProject = false,
            EditProject = false,
            DeleteProject = false,
            ViewKanbanBoard = true,
            AccessToProjectUiEditor = true,

            ProjectModalWindow = false,
            SetProjectOwner = false,
            SetProjectMembers = false,
            SetProjectClient = false,
            AddProjectFiles = false,

            ChangeProjectTaskStatus = true,
            ImportTasksFromFormula = false,
            CreateProjectTask = false,
            EditProjectTask = false,
            DeleteProjectTask = false,
            SelectOptionOnCompleteProjectTask = false,
            ChangeChecklistItemStatus = true,
            FilterTasksBySkill = false,
            FilterTasksByUser = false,

            ProjectUiEditorCreateTask = false,
            ProjectUiEditorEditTask = false,
            ProjectUiEditorDeleteTask = false,
            ProjectUiEditorAddTaskConnection = false,
            ProjectUiEditorRemoveTaskConnection = false,

            CanChangeProcessingUser = false,
            CanAssignVendor = false,
            CanStopOutsource = true,
            ProjectTaskEditorModal = true,
            ProjectTaskEditorModalViewNotEdit = true,
            ProjectTaskEditorModalSetStartDate = false,
            ProjectTaskEditorModalSetDueDate = false,
            ProjectTaskEditorModalSetDuration = false,
            ProjectTaskEditorModalSetMembers = false,
            ProjectTaskEditorModalSetRecurringOptions = false,
            ProjectTaskEditorModalProfiles = false,
            ProjectTaskEditorModalFiles = true,
            ProjectTaskEditorModalEditCondition = false,
            ProjectTaskEditorModalAddConditionOption = false,
            ProjectTaskEditorModalEditConditionOption = false,
            ProjectTaskEditorModalDeleteConditionOption = false,
            ProjectTaskEditorModalAssignConditionOptionToTask = false,
            ProjectTaskEditorModalCreateChecklist = false,
            ProjectTaskEditorModalEditChecklist = false,
            ProjectTaskEditorModalDeleteChecklistItem = false,
            ProjectTaskEditorModalToggleChecklistItem = true,

            UsersPage = false,
            CreateUser = false,
            EditUsersName = true,
            ChangeUsersRole = false,
            DeleteUser = false,
            LockUser = false,
            UnlockUser = false,
            EditUserNotificationSettings = false,
            EditRoleNotificationSettings = false,

            EditOwnerBusinessDetails = false,
            ViewOwnerBusinessDetails = false,

            SkillsPage = false,
            TeamsPage = false,
            CreateTeam = false,
            ReadSkill = false,
            CreateSkill = false,
            EditSkill = false,
            DeleteSkill = false,
            AssignSkill = false,
            ReadUserSkill = true,
            AddUserToSkill = false,

            ClientsPage = false,
            CreateClient = false,
            ReadClient = false,
            EditClient = false,
            DeleteClient = false,
            AssignProjectToClient = false,

            BalancePage = true,
            CreditsPage = false,

            ViewMissionControl = true,

            ViewUpSkills = true,

            FormulaTaskLockTraining = false,
        }; // added new for company (WRT Sprint 10B)
    }
}
